In [20]:
# Importar librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
# Cargar datos
r2018 = pd.read_csv('data/rendimiento/2018/r2018.csv', encoding='latin-1', sep=';')
r2019 = pd.read_csv('data/rendimiento/2019/r2019.csv', encoding='latin-1', sep=';')

/var/folders/lm/4_3myv813nlbx14xpgrgx5l00000gn/T/ipykernel_93192/2361527491.py:2: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  r2018 = pd.read_csv('data/rendimiento/2018/r2018.csv', encoding='latin-1', sep=';')
/var/folders/lm/4_3myv813nlbx14xpgrgx5l00000gn/T/ipykernel_93192/2361527491.py:3: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  r2019 = pd.read_csv('data/rendimiento/2019/r2019.csv', encoding='latin-1', sep=';')

In [22]:
# Cambiar nombre de variable 'ï»¿AGNO' por 'AGNO'
r2018.rename(columns={'ï»¿AGNO':'AGNO'}, inplace=True)

In [23]:
r2018.head()

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,COD_REG_ALU,COD_COM_ALU,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R
0,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,400,410,41001,0,0,Y,T
1,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,400,410,41001,0,0,Y,Y
2,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,400,410,41001,0,0,Y,T
3,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,400,410,41001,"6,4",95,P,P
4,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15,15101,ARICA,400,410,41001,0,0,Y,Y

In [24]:
r2019.rename(columns={'ï»¿AGNO':'AGNO'}, inplace=True)
r2019.head()

,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,COD_DEPROV_RBD,...,COD_COM_ALU,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R,COD_MEN
0,2019,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,5,85,P,P,0
1,2019,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,0,0,Y,Y,0
2,2019,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,"4,9",89,R,R,0
3,2019,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,15101,ARICA,400,410,41001,0,0,Y,Y,0
4,2019,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,151,...,1107,ALTO HOSPICIO,400,410,41001,0,0,Y,T,0

In [25]:
r2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3293750 entries, 0 to 3293749
Data columns (total 36 columns):
 #   Column          Dtype
---  ------          -----
 0   AGNO            int64
 1   RBD             int64
 2   DGV_RBD         int64
 3   NOM_RBD         object
 4   COD_REG_RBD     int64
 5   NOM_REG_RBD_A   object
 6   COD_PRO_RBD     int64
 7   COD_COM_RBD     int64
 8   NOM_COM_RBD     object
 9   COD_DEPROV_RBD  int64
 10  NOM_DEPROV_RBD  object
 11  COD_DEPE        int64
 12  COD_DEPE2       int64
 13  RURAL_RBD       int64
 14  ESTADO_ESTAB    int64
 15  COD_ENSE        int64
 16  COD_ENSE2       int64
 17  COD_GRADO       int64
 18  LET_CUR         object
 19  COD_JOR         int64
 20  COD_TIP_CUR     int64
 21  COD_DES_CUR     int64
 22  MRUN            int64
 23  GEN_ALU         int64
 24  FEC_NAC_ALU     int64
 25  EDAD_ALU        object
 26  COD_REG_ALU     int64
 27  COD_COM_ALU     int64
 28  NOM_COM_ALU     object
 29  COD_RAMA        int64
 30  COD_SEC         int64
 31  COD_ESPE        int64
 32  PROM_GRAL       object
 33  ASISTENCIA      int64
 34  SIT_FIN         object
 35  SIT_FIN_R       object
dtypes: int64(26), object(10)
memory usage: 904.7+ MB

In [26]:
r2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3328915 entries, 0 to 3328914
Data columns (total 37 columns):
 #   Column          Dtype
---  ------          -----
 0   AGNO            int64
 1   RBD             int64
 2   DGV_RBD         int64
 3   NOM_RBD         object
 4   COD_REG_RBD     int64
 5   NOM_REG_RBD_A   object
 6   COD_PRO_RBD     int64
 7   COD_COM_RBD     int64
 8   NOM_COM_RBD     object
 9   COD_DEPROV_RBD  int64
 10  NOM_DEPROV_RBD  object
 11  COD_DEPE        int64
 12  COD_DEPE2       int64
 13  RURAL_RBD       int64
 14  ESTADO_ESTAB    int64
 15  COD_ENSE        int64
 16  COD_ENSE2       int64
 17  COD_GRADO       int64
 18  LET_CUR         object
 19  COD_JOR         int64
 20  COD_TIP_CUR     int64
 21  COD_DES_CUR     int64
 22  MRUN            int64
 23  GEN_ALU         int64
 24  FEC_NAC_ALU     int64
 25  EDAD_ALU        object
 26  COD_REG_ALU     int64
 27  COD_COM_ALU     int64
 28  NOM_COM_ALU     object
 29  COD_RAMA        int64
 30  COD_SEC         int64
 31  COD_ESPE        int64
 32  PROM_GRAL       object
 33  ASISTENCIA      int64
 34  SIT_FIN         object
 35  SIT_FIN_R       object
 36  COD_MEN         int64
dtypes: int64(27), object(10)
memory usage: 939.7+ MB

In [27]:
from analisis2 import desertoresr

In [28]:
desertoresr(r2018, r2019)

/Users/borisbravo/Documents/desercion-escolar/analisis2.py:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  desertores = desertores[~((desertores['COD_GRADO'] == 4) & (df_anterior['COD_ENSE2'].isin([5, 7])))]
/Users/borisbravo/Documents/desercion-escolar/analisis2.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  estudiantes_regulares['DESERTOR'] = 0

In [29]:
df = pd.read_csv('data/tablas/combinado2018.csv', encoding='latin-1', sep=';')

In [30]:
df.head()

,Unnamed: 0,AGNO,RBD,DGV_RBD,NOM_RBD,COD_REG_RBD,NOM_REG_RBD_A,COD_PRO_RBD,COD_COM_RBD,NOM_COM_RBD,...,NOM_COM_ALU,COD_RAMA,COD_SEC,COD_ESPE,PROM_GRAL,ASISTENCIA,SIT_FIN,SIT_FIN_R,DESERTOR,COD_MEN
0,25,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,...,ARICA,0,0,0,"4,3",76,R,R,1,NaN
1,26,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,...,ARICA,0,0,0,0,0,Y,T,1,NaN
2,56,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,...,ARICA,0,0,0,0,0,Y,T,1,NaN
3,59,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,...,POZO ALMONTE,0,0,0,0,0,Y,Y,1,NaN
4,61,2018,1,9,LICEO POLITECNICO ARICA,15,AYP,151,15101,ARICA,...,ARICA,0,0,0,0,0,Y,Y,1,NaN

In [31]:
# eliminar unnamed
df.drop(columns=['Unnamed: 0'], inplace=True)

In [32]:
# Valores unicos de variable DESERTORES
df['DESERTOR'].value_counts()

DESERTOR
0    2813885
1      79315
Name: count, dtype: int64

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2893200 entries, 0 to 2893199
Data columns (total 38 columns):
 #   Column          Dtype
---  ------          -----
 0   AGNO            int64
 1   RBD             int64
 2   DGV_RBD         int64
 3   NOM_RBD         object
 4   COD_REG_RBD     int64
 5   NOM_REG_RBD_A   object
 6   COD_PRO_RBD     int64
 7   COD_COM_RBD     int64
 8   NOM_COM_RBD     object
 9   COD_DEPROV_RBD  int64
 10  NOM_DEPROV_RBD  object
 11  COD_DEPE        int64
 12  COD_DEPE2       int64
 13  RURAL_RBD       int64
 14  ESTADO_ESTAB    int64
 15  COD_ENSE        int64
 16  COD_ENSE2       int64
 17  COD_GRADO       int64
 18  LET_CUR         object
 19  COD_JOR         int64
 20  COD_TIP_CUR     int64
 21  COD_DES_CUR     int64
 22  MRUN            int64
 23  GEN_ALU         int64
 24  FEC_NAC_ALU     int64
 25  EDAD_ALU        int64
 26  COD_REG_ALU     int64
 27  COD_COM_ALU     int64
 28  NOM_COM_ALU     object
 29  COD_RAMA        int64
 30  COD_SEC         int64
 31  COD_ESPE        int64
 32  PROM_GRAL       object
 33  ASISTENCIA      int64
 34  SIT_FIN         object
 35  SIT_FIN_R       object
 36  DESERTOR        int64
 37  COD_MEN         float64
dtypes: float64(1), int64(28), object(9)
memory usage: 838.8+ MB

In [34]:
# drop NOM_RBD, NOM_COM_RBD, NOM_DEPROV_RBD
df.drop(columns=['NOM_RBD', 'NOM_COM_RBD', 'NOM_DEPROV_RBD', 'LET_CUR'], inplace=True)

In [36]:
# Lista de nombre de variables 
list(df.columns)

['AGNO',
 'RBD',
 'DGV_RBD',
 'COD_REG_RBD',
 'NOM_REG_RBD_A',
 'COD_PRO_RBD',
 'COD_COM_RBD',
 'COD_DEPROV_RBD',
 'COD_DEPE',
 'COD_DEPE2',
 'RURAL_RBD',
 'ESTADO_ESTAB',
 'COD_ENSE',
 'COD_ENSE2',
 'COD_GRADO',
 'COD_JOR',
 'COD_TIP_CUR',
 'COD_DES_CUR',
 'MRUN',
 'GEN_ALU',
 'FEC_NAC_ALU',
 'EDAD_ALU',
 'COD_REG_ALU',
 'COD_COM_ALU',
 'NOM_COM_ALU',
 'COD_RAMA',
 'COD_SEC',
 'COD_ESPE',
 'PROM_GRAL',
 'ASISTENCIA',
 'SIT_FIN',
 'SIT_FIN_R',
 'DESERTOR',
 'COD_MEN']

In [37]:
# lista de variables object
df.select_dtypes(include=['object']).columns

Index(['NOM_REG_RBD_A', 'NOM_COM_ALU', 'PROM_GRAL', 'SIT_FIN', 'SIT_FIN_R'], dtype='object')

In [38]:
# Drop Unnamed, 'NOM_REG_RBD_A', 'NOM_COM_ALU'
df.drop(columns=['NOM_REG_RBD_A', 'NOM_COM_ALU'], inplace=True)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2893200 entries, 0 to 2893199
Data columns (total 32 columns):
 #   Column          Dtype
---  ------          -----
 0   AGNO            int64
 1   RBD             int64
 2   DGV_RBD         int64
 3   COD_REG_RBD     int64
 4   COD_PRO_RBD     int64
 5   COD_COM_RBD     int64
 6   COD_DEPROV_RBD  int64
 7   COD_DEPE        int64
 8   COD_DEPE2       int64
 9   RURAL_RBD       int64
 10  ESTADO_ESTAB    int64
 11  COD_ENSE        int64
 12  COD_ENSE2       int64
 13  COD_GRADO       int64
 14  COD_JOR         int64
 15  COD_TIP_CUR     int64
 16  COD_DES_CUR     int64
 17  MRUN            int64
 18  GEN_ALU         int64
 19  FEC_NAC_ALU     int64
 20  EDAD_ALU        int64
 21  COD_REG_ALU     int64
 22  COD_COM_ALU     int64
 23  COD_RAMA        int64
 24  COD_SEC         int64
 25  COD_ESPE        int64
 26  PROM_GRAL       object
 27  ASISTENCIA      int64
 28  SIT_FIN         object
 29  SIT_FIN_R       object
 30  DESERTOR        int64
 31  COD_MEN         float64
dtypes: float64(1), int64(28), object(3)
memory usage: 706.3+ MB

In [40]:
# df2018 dESERTOR valores unicos
df['DESERTOR'].unique()

array([1, 0])

In [42]:
# list variables names
list(df.columns)

['AGNO',
 'RBD',
 'DGV_RBD',
 'COD_REG_RBD',
 'COD_PRO_RBD',
 'COD_COM_RBD',
 'COD_DEPROV_RBD',
 'COD_DEPE',
 'COD_DEPE2',
 'RURAL_RBD',
 'ESTADO_ESTAB',
 'COD_ENSE',
 'COD_ENSE2',
 'COD_GRADO',
 'COD_JOR',
 'COD_TIP_CUR',
 'COD_DES_CUR',
 'MRUN',
 'GEN_ALU',
 'FEC_NAC_ALU',
 'EDAD_ALU',
 'COD_REG_ALU',
 'COD_COM_ALU',
 'COD_RAMA',
 'COD_SEC',
 'COD_ESPE',
 'PROM_GRAL',
 'ASISTENCIA',
 'SIT_FIN',
 'SIT_FIN_R',
 'DESERTOR',
 'COD_MEN']

In [43]:
# PROM_GRAL change , for . the datatyope is float
df['PROM_GRAL'] = df['PROM_GRAL'].str.replace(',', '.').astype(float)

In [44]:
# list variables object
df.select_dtypes(include=['object']).columns

Index(['SIT_FIN', 'SIT_FIN_R'], dtype='object')

In [45]:
# dummies 'SIT_FIN', 'SIT_FIN_R'
df = pd.get_dummies(df, columns=['SIT_FIN', 'SIT_FIN_R'])

In [46]:
# df2018 variables category
df.select_dtypes(include=['category']).columns

Index([], dtype='object')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2893200 entries, 0 to 2893199
Data columns (total 39 columns):
 #   Column          Dtype
---  ------          -----
 0   AGNO            int64
 1   RBD             int64
 2   DGV_RBD         int64
 3   COD_REG_RBD     int64
 4   COD_PRO_RBD     int64
 5   COD_COM_RBD     int64
 6   COD_DEPROV_RBD  int64
 7   COD_DEPE        int64
 8   COD_DEPE2       int64
 9   RURAL_RBD       int64
 10  ESTADO_ESTAB    int64
 11  COD_ENSE        int64
 12  COD_ENSE2       int64
 13  COD_GRADO       int64
 14  COD_JOR         int64
 15  COD_TIP_CUR     int64
 16  COD_DES_CUR     int64
 17  MRUN            int64
 18  GEN_ALU         int64
 19  FEC_NAC_ALU     int64
 20  EDAD_ALU        int64
 21  COD_REG_ALU     int64
 22  COD_COM_ALU     int64
 23  COD_RAMA        int64
 24  COD_SEC         int64
 25  COD_ESPE        int64
 26  PROM_GRAL       float64
 27  ASISTENCIA      int64
 28  DESERTOR        int64
 29  COD_MEN         float64
 30  SIT_FIN_        bool
 31  SIT_FIN_P       bool
 32  SIT_FIN_R       bool
 33  SIT_FIN_Y       bool
 34  SIT_FIN_R_      bool
 35  SIT_FIN_R_P     bool
 36  SIT_FIN_R_R     bool
 37  SIT_FIN_R_T     bool
 38  SIT_FIN_R_Y     bool
dtypes: bool(9), float64(2), int64(28)
memory usage: 687.0 MB

In [48]:
# Datos nulos
df.isnull().sum()

AGNO                  0
RBD                   0
DGV_RBD               0
COD_REG_RBD           0
COD_PRO_RBD           0
COD_COM_RBD           0
COD_DEPROV_RBD        0
COD_DEPE              0
COD_DEPE2             0
RURAL_RBD             0
ESTADO_ESTAB          0
COD_ENSE              0
COD_ENSE2             0
COD_GRADO             0
COD_JOR               0
COD_TIP_CUR           0
COD_DES_CUR           0
MRUN                  0
GEN_ALU               0
FEC_NAC_ALU           0
EDAD_ALU              0
COD_REG_ALU           0
COD_COM_ALU           0
COD_RAMA              0
COD_SEC               0
COD_ESPE              0
PROM_GRAL             0
ASISTENCIA            0
DESERTOR              0
COD_MEN           79315
SIT_FIN_              0
SIT_FIN_P             0
SIT_FIN_R             0
SIT_FIN_Y             0
SIT_FIN_R_            0
SIT_FIN_R_P           0
SIT_FIN_R_R           0
SIT_FIN_R_T           0
SIT_FIN_R_Y           0
dtype: int64

In [49]:
# Drop variable COD_MEN
df.drop(columns=['COD_MEN'], inplace=True)

In [50]:
# Datos nulos
df.isnull().sum()

AGNO              0
RBD               0
DGV_RBD           0
COD_REG_RBD       0
COD_PRO_RBD       0
COD_COM_RBD       0
COD_DEPROV_RBD    0
COD_DEPE          0
COD_DEPE2         0
RURAL_RBD         0
ESTADO_ESTAB      0
COD_ENSE          0
COD_ENSE2         0
COD_GRADO         0
COD_JOR           0
COD_TIP_CUR       0
COD_DES_CUR       0
MRUN              0
GEN_ALU           0
FEC_NAC_ALU       0
EDAD_ALU          0
COD_REG_ALU       0
COD_COM_ALU       0
COD_RAMA          0
COD_SEC           0
COD_ESPE          0
PROM_GRAL         0
ASISTENCIA        0
DESERTOR          0
SIT_FIN_          0
SIT_FIN_P         0
SIT_FIN_R         0
SIT_FIN_Y         0
SIT_FIN_R_        0
SIT_FIN_R_P       0
SIT_FIN_R_R       0
SIT_FIN_R_T       0
SIT_FIN_R_Y       0
dtype: int64

In [54]:
df.drop(columns=['DESERTOR'], inplace=True)

In [51]:
# Random Forest d2018   
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

In [56]:
df.columns

Index(['AGNO', 'RBD', 'DGV_RBD', 'COD_REG_RBD', 'COD_PRO_RBD', 'COD_COM_RBD',
       'COD_DEPROV_RBD', 'COD_DEPE', 'COD_DEPE2', 'RURAL_RBD', 'ESTADO_ESTAB',
       'COD_ENSE', 'COD_ENSE2', 'COD_GRADO', 'COD_JOR', 'COD_TIP_CUR',
       'COD_DES_CUR', 'MRUN', 'GEN_ALU', 'FEC_NAC_ALU', 'EDAD_ALU',
       'COD_REG_ALU', 'COD_COM_ALU', 'COD_RAMA', 'COD_SEC', 'COD_ESPE',
       'PROM_GRAL', 'ASISTENCIA', 'SIT_FIN_ ', 'SIT_FIN_P', 'SIT_FIN_R',
       'SIT_FIN_Y', 'SIT_FIN_R_ ', 'SIT_FIN_R_P', 'SIT_FIN_R_R', 'SIT_FIN_R_T',
       'SIT_FIN_R_Y'],
      dtype='object')

In [ ]:
# 9, 10, 14, 15, 16, 18, 23, 24, 28, 29, 30, 31, 32, 33, 34, 35, 36
# RURAL_RBD, ESTADO_ESTAB, COD_JOR, COD_TIP_CUR, COD_DES_CUR, GEN_ALU, COD_RAMA, COD_SEC, SIT_FIN_ ', 'SIT_FIN_P', 'SIT_FIN_R', 'SIT_FIN_Y', 'SIT_FIN_R_ ', 'SIT_FIN_R_P', 'SIT_FIN_R_R', 'SIT_FIN_R_T', 'SIT_FIN_R_Y'

In [59]:
from kmodes.kprototypes import KPrototypes

# Definir el número de clusters
num_clusters = 3

# Crear una instancia de KPrototypes
kproto = KPrototypes(n_clusters=num_clusters, init='Cao', verbose=2)

# Ajustar el modelo a los datos
clusters = kproto.fit_predict(df, categorical=[9, 10, 14, 15, 16, 18, 23, 24, 28, 29, 30, 31, 32, 33, 34, 35, 36])

# Añadir las etiquetas de los clusters al dataframe
df['Cluster'] = clusters

Initialization method and algorithm are deterministic. Setting n_init to 1.
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/100, moves: 309108, ncost: 1.8172432883704302e+19
Run: 1, iteration: 2/100, moves: 80498, ncost: 1.7970377479079131e+19
Run: 1, iteration: 3/100, moves: 47723, ncost: 1.7908880751213404e+19
Run: 1, iteration: 4/100, moves: 28021, ncost: 1.7887981072023605e+19
Run: 1, iteration: 5/100, moves: 16082, ncost: 1.7881078009105924e+19
Run: 1, iteration: 6/100, moves: 9422, ncost: 1.78787121222515e+19
Run: 1, iteration: 7/100, moves: 5450, ncost: 1.7877923471657726e+19
Run: 1, iteration: 8/100, moves: 3073, ncost: 1.7877669179065369e+19
Run: 1, iteration: 9/100, moves: 1761, ncost: 1.7877584146631176e+19
Run: 1, iteration: 10/100, moves: 1028, ncost: 1.7877555533813543e+19
Run: 1, iteration: 11/100, moves: 542, ncost: 1.787754723428806e+19
Run: 1, iteration: 12/100, moves: 355, ncost: 1.7877543943288439e+19
Run: 1, iteration: 13/100, moves: 178, ncost: 1.787754305169252e+19
Run: 1, iteration: 14/100, moves: 118, ncost: 1.7877542707187245e+19
Run: 1, iteration: 15/100, moves: 76, ncost: 1.7877542553715503e+19
Run: 1, iteration: 16/100, moves: 43, ncost: 1.7877542504428059e+19
Run: 1, iteration: 17/100, moves: 23, ncost: 1.7877542484473119e+19
Run: 1, iteration: 18/100, moves: 24, ncost: 1.7877542468712417e+19
Run: 1, iteration: 19/100, moves: 13, ncost: 1.7877542464547842e+19
Run: 1, iteration: 20/100, moves: 4, ncost: 1.787754246390851e+19
Run: 1, iteration: 21/100, moves: 2, ncost: 1.7877542463793795e+19
Run: 1, iteration: 22/100, moves: 0, ncost: 1.7877542463793795e+19
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 2, iteration: 1/100, moves: 304280, ncost: 1.8212647121034322e+19
Run: 2, iteration: 2/100, moves: 86120, ncost: 1.7984629898482758e+19
Run: 2, iteration: 3/100, moves: 51290, ncost: 1.7913723792803434e+19
Run: 2, iteration: 4/100, moves: 29933, ncost: 1.7889696517790308e+19
Run: 2, iteration: 5/100, moves: 17301, ncost: 1.7881675602254465e+19
Run: 2, iteration: 6/100, moves: 10200, ncost: 1.787890950859623e+19
Run: 2, iteration: 7/100, moves: 5887, ncost: 1.7877988320157334e+19
Run: 2, iteration: 8/100, moves: 3356, ncost: 1.7877688382840519e+19
Run: 2, iteration: 9/100, moves: 1902, ncost: 1.7877590251138945e+19
Run: 2, iteration: 10/100, moves: 1111, ncost: 1.7877557239161612e+19
Run: 2, iteration: 11/100, moves: 588, ncost: 1.7877547691475677e+19
Run: 2, iteration: 12/100, moves: 366, ncost: 1.7877544129885743e+19
Run: 2, iteration: 13/100, moves: 201, ncost: 1.7877543071866483e+19
Run: 2, iteration: 14/100, moves: 119, ncost: 1.7877542715687082e+19
Run: 2, iteration: 15/100, moves: 79, ncost: 1.7877542555356051e+19
Run: 2, iteration: 16/100, moves: 44, ncost: 1.7877542504428059e+19
Run: 2, iteration: 17/100, moves: 23, ncost: 1.7877542484473119e+19
Run: 2, iteration: 18/100, moves: 24, ncost: 1.7877542468712417e+19
Run: 2, iteration: 19/100, moves: 13, ncost: 1.7877542464547842e+19
Run: 2, iteration: 20/100, moves: 4, ncost: 1.787754246390851e+19
Run: 2, iteration: 21/100, moves: 2, ncost: 1.7877542463793795e+19
Run: 2, iteration: 22/100, moves: 0, ncost: 1.7877542463793795e+19
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 3, iteration: 1/100, moves: 434613, ncost: 1.8043715955098188e+19
Run: 3, iteration: 2/100, moves: 73147, ncost: 1.7918387598987082e+19
Run: 3, iteration: 3/100, moves: 31578, ncost: 1.7891014722899773e+19
Run: 3, iteration: 4/100, moves: 18255, ncost: 1.7882102717762888e+19
Run: 3, iteration: 5/100, moves: 10640, ncost: 1.7879068130715898e+19
Run: 3, iteration: 6/100, moves: 6197, ncost: 1.7878042945349102e+19
Run: 3, iteration: 7/100, moves: 3535, ncost: 1.7877707444193e+19
Run: 3, iteration: 8/100, moves: 2022, ncost: 1.7877596712920562e+19
Run: 3, iteration: 9/100, moves: 1194, ncost: 1.7877559014795713e+19
Run: 3, iteration: 10/100, moves: 648, ncost: 1.7877547972560167e+19
Run: 3, iteration: 11/100, moves: 376, ncost: 1.7877544221948135e+19
Run: 3, iteration: 12/100, moves: 197, ncost: 1.7877543136837544e+19
Run: 3, iteration: 13/100, moves: 119, ncost: 1.787754275115074e+19
Run: 3, iteration: 14/100, moves: 76, ncost: 1.7877542589589058e+19
Run: 3, iteration: 15/100, moves: 52, ncost: 1.7877542517759623e+19
Run: 3, iteration: 16/100, moves: 29, ncost: 1.787754248940036e+19
Run: 3, iteration: 17/100, moves: 28, ncost: 1.7877542469552517e+19
Run: 3, iteration: 18/100, moves: 15, ncost: 1.7877542464547842e+19
Run: 3, iteration: 19/100, moves: 4, ncost: 1.787754246390851e+19
Run: 3, iteration: 20/100, moves: 2, ncost: 1.7877542463793795e+19
Run: 3, iteration: 21/100, moves: 0, ncost: 1.7877542463793795e+19
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 4, iteration: 1/100, moves: 330323, ncost: 1.7932267989362125e+19
Run: 4, iteration: 2/100, moves: 53224, ncost: 1.788763127869715e+19
Run: 4, iteration: 3/100, moves: 15539, ncost: 1.788080684347294e+19
Run: 4, iteration: 4/100, moves: 9015, ncost: 1.7878641158169334e+19
Run: 4, iteration: 5/100, moves: 5197, ncost: 1.78779185227277e+19
Run: 4, iteration: 6/100, moves: 3062, ncost: 1.7877669707382565e+19
Run: 4, iteration: 7/100, moves: 1793, ncost: 1.7877584918058854e+19
Run: 4, iteration: 8/100, moves: 1008, ncost: 1.787755738308804e+19
Run: 4, iteration: 9/100, moves: 602, ncost: 1.7877547700544422e+19
Run: 4, iteration: 10/100, moves: 377, ncost: 1.7877543925382621e+19
Run: 4, iteration: 11/100, moves: 216, ncost: 1.7877542749214386e+19
Run: 4, iteration: 12/100, moves: 104, ncost: 1.787754251468046e+19
Run: 4, iteration: 13/100, moves: 34, ncost: 1.7877542480190786e+19
Run: 4, iteration: 14/100, moves: 19, ncost: 1.7877542470872383e+19
Run: 4, iteration: 15/100, moves: 15, ncost: 1.7877542465073148e+19
Run: 4, iteration: 16/100, moves: 7, ncost: 1.7877542463793795e+19
Run: 4, iteration: 17/100, moves: 0, ncost: 1.7877542463793795e+19
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 5, iteration: 1/100, moves: 404219, ncost: 2.0895389832674922e+19
Run: 5, iteration: 2/100, moves: 267579, ncost: 1.888411801363007e+19
Run: 5, iteration: 3/100, moves: 157883, ncost: 1.8214433059938103e+19
Run: 5, iteration: 4/100, moves: 91744, ncost: 1.7989699230745194e+19
Run: 5, iteration: 5/100, moves: 52938, ncost: 1.7915174942776113e+19
Run: 5, iteration: 6/100, moves: 30712, ncost: 1.7890063036049893e+19
Run: 5, iteration: 7/100, moves: 17718, ncost: 1.7881714513706793e+19
Run: 5, iteration: 8/100, moves: 10206, ncost: 1.787894678283124e+19
Run: 5, iteration: 9/100, moves: 5856, ncost: 1.787802426634115e+19
Run: 5, iteration: 10/100, moves: 3440, ncost: 1.7877707910218578e+19
Run: 5, iteration: 11/100, moves: 2041, ncost: 1.7877597615243997e+19
Run: 5, iteration: 12/100, moves: 1163, ncost: 1.7877561480673255e+19
Run: 5, iteration: 13/100, moves: 689, ncost: 1.7877549103940602e+19
Run: 5, iteration: 14/100, moves: 422, ncost: 1.787754434658829e+19
Run: 5, iteration: 15/100, moves: 233, ncost: 1.7877542882438443e+19
Run: 5, iteration: 16/100, moves: 123, ncost: 1.7877542546198088e+19
Run: 5, iteration: 17/100, moves: 46, ncost: 1.787754248569882e+19
Run: 5, iteration: 18/100, moves: 24, ncost: 1.7877542472707201e+19
Run: 5, iteration: 19/100, moves: 19, ncost: 1.7877542465073148e+19
Run: 5, iteration: 20/100, moves: 7, ncost: 1.7877542463793795e+19
Run: 5, iteration: 21/100, moves: 0, ncost: 1.7877542463793795e+19
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 6, iteration: 1/100, moves: 391846, ncost: 2.0894993312330785e+19
Run: 6, iteration: 2/100, moves: 268243, ncost: 1.8904263407061336e+19
Run: 6, iteration: 3/100, moves: 159606, ncost: 1.8221327048589152e+19
Run: 6, iteration: 4/100, moves: 92735, ncost: 1.7991902025507764e+19
Run: 6, iteration: 5/100, moves: 53442, ncost: 1.791592717363937e+19
Run: 6, iteration: 6/100, moves: 31018, ncost: 1.7890313733011919e+19
Run: 6, iteration: 7/100, moves: 17899, ncost: 1.7881796370831235e+19
Run: 6, iteration: 8/100, moves: 10284, ncost: 1.7878978303341976e+19
Run: 6, iteration: 9/100, moves: 5925, ncost: 1.7878034693232798e+19
Run: 6, iteration: 10/100, moves: 3479, ncost: 1.787771133777333e+19
Run: 6, iteration: 11/100, moves: 2060, ncost: 1.7877598845710584e+19
Run: 6, iteration: 12/100, moves: 1179, ncost: 1.7877561829073695e+19
Run: 6, iteration: 13/100, moves: 690, ncost: 1.787754930259815e+19
Run: 6, iteration: 14/100, moves: 424, ncost: 1.7877544447435753e+19
Run: 6, iteration: 15/100, moves: 231, ncost: 1.7877542941514842e+19
Run: 6, iteration: 16/100, moves: 125, ncost: 1.7877542567395934e+19
Run: 6, iteration: 17/100, moves: 44, ncost: 1.787754249988791e+19
Run: 6, iteration: 18/100, moves: 24, ncost: 1.7877542479808207e+19
Run: 6, iteration: 19/100, moves: 18, ncost: 1.7877542470872383e+19
Run: 6, iteration: 20/100, moves: 15, ncost: 1.7877542465073148e+19
Run: 6, iteration: 21/100, moves: 7, ncost: 1.7877542463793795e+19
Run: 6, iteration: 22/100, moves: 0, ncost: 1.7877542463793795e+19
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 7, iteration: 1/100, moves: 248729, ncost: 1.854059785620726e+19
Run: 7, iteration: 2/100, moves: 124291, ncost: 1.8097646193873857e+19
Run: 7, iteration: 3/100, moves: 73792, ncost: 1.7951285847821353e+19
Run: 7, iteration: 4/100, moves: 42700, ncost: 1.7902455399902419e+19
Run: 7, iteration: 5/100, moves: 25022, ncost: 1.7885812346806596e+19
Run: 7, iteration: 6/100, moves: 14267, ncost: 1.7880341100861618e+19
Run: 7, iteration: 7/100, moves: 8316, ncost: 1.7878490943185457e+19
Run: 7, iteration: 8/100, moves: 4854, ncost: 1.7877865268475955e+19
Run: 7, iteration: 9/100, moves: 2892, ncost: 1.7877648651334294e+19
Run: 7, iteration: 10/100, moves: 1656, ncost: 1.7877577320475746e+19
Run: 7, iteration: 11/100, moves: 907, ncost: 1.7877554929716716e+19
Run: 7, iteration: 12/100, moves: 525, ncost: 1.7877547016769464e+19
Run: 7, iteration: 13/100, moves: 356, ncost: 1.7877543699291814e+19
Run: 7, iteration: 14/100, moves: 198, ncost: 1.7877542706179402e+19
Run: 7, iteration: 15/100, moves: 89, ncost: 1.787754251468046e+19
Run: 7, iteration: 16/100, moves: 34, ncost: 1.7877542480190786e+19
Run: 7, iteration: 17/100, moves: 19, ncost: 1.7877542470872383e+19
Run: 7, iteration: 18/100, moves: 15, ncost: 1.7877542465073148e+19
Run: 7, iteration: 19/100, moves: 7, ncost: 1.7877542463793795e+19
Run: 7, iteration: 20/100, moves: 0, ncost: 1.7877542463793795e+19
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 8, iteration: 1/100, moves: 439154, ncost: 1.873600413029243e+19
Run: 8, iteration: 2/100, moves: 139162, ncost: 1.8149172474238681e+19
Run: 8, iteration: 3/100, moves: 81979, ncost: 1.7968069070670193e+19
Run: 8, iteration: 4/100, moves: 47392, ncost: 1.7908052426307082e+19
Run: 8, iteration: 5/100, moves: 27642, ncost: 1.788769800609339e+19
Run: 8, iteration: 6/100, moves: 15872, ncost: 1.7880955740254415e+19
Run: 8, iteration: 7/100, moves: 9218, ncost: 1.7878694004828879e+19
Run: 8, iteration: 8/100, moves: 5302, ncost: 1.787793847618291e+19
Run: 8, iteration: 9/100, moves: 3129, ncost: 1.7877677463074916e+19
Run: 8, iteration: 10/100, moves: 1840, ncost: 1.7877587669441757e+19
Run: 8, iteration: 11/100, moves: 1053, ncost: 1.7877558066742501e+19
Run: 8, iteration: 12/100, moves: 620, ncost: 1.7877547909855863e+19
Run: 8, iteration: 13/100, moves: 384, ncost: 1.7877543988230425e+19
Run: 8, iteration: 14/100, moves: 221, ncost: 1.7877542761086284e+19
Run: 8, iteration: 15/100, moves: 104, ncost: 1.7877542519992678e+19
Run: 8, iteration: 16/100, moves: 37, ncost: 1.7877542480723659e+19
Run: 8, iteration: 17/100, moves: 20, ncost: 1.7877542470872383e+19
Run: 8, iteration: 18/100, moves: 15, ncost: 1.7877542465073148e+19
Run: 8, iteration: 19/100, moves: 7, ncost: 1.7877542463793795e+19
Run: 8, iteration: 20/100, moves: 0, ncost: 1.7877542463793795e+19
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 9, iteration: 1/100, moves: 686327, ncost: 1.8167695556426537e+19
Run: 9, iteration: 2/100, moves: 114329, ncost: 1.7933876330640093e+19
Run: 9, iteration: 3/100, moves: 36944, ncost: 1.7895746337535732e+19
Run: 9, iteration: 4/100, moves: 21220, ncost: 1.788368617816999e+19
Run: 9, iteration: 5/100, moves: 12418, ncost: 1.7879590717190406e+19
Run: 9, iteration: 6/100, moves: 7061, ncost: 1.7878231518620592e+19
Run: 9, iteration: 7/100, moves: 4180, ncost: 1.787776703611787e+19
Run: 9, iteration: 8/100, moves: 2433, ncost: 1.7877613158583046e+19
Run: 9, iteration: 9/100, moves: 1376, ncost: 1.7877563809227522e+19
Run: 9, iteration: 10/100, moves: 749, ncost: 1.7877549254093961e+19
Run: 9, iteration: 11/100, moves: 429, ncost: 1.7877544575899337e+19
Run: 9, iteration: 12/100, moves: 226, ncost: 1.7877543207287063e+19
Run: 9, iteration: 13/100, moves: 127, ncost: 1.7877542771579853e+19
Run: 9, iteration: 14/100, moves: 82, ncost: 1.787754259705846e+19
Run: 9, iteration: 15/100, moves: 51, ncost: 1.7877542523251286e+19
Run: 9, iteration: 16/100, moves: 32, ncost: 1.7877542490641046e+19
Run: 9, iteration: 17/100, moves: 25, ncost: 1.7877542472762452e+19
Run: 9, iteration: 18/100, moves: 16, ncost: 1.787754246561361e+19
Run: 9, iteration: 19/100, moves: 6, ncost: 1.7877542464159533e+19
Run: 9, iteration: 20/100, moves: 3, ncost: 1.787754246383263e+19
Run: 9, iteration: 21/100, moves: 1, ncost: 1.7877542463793795e+19
Run: 9, iteration: 22/100, moves: 0, ncost: 1.7877542463793795e+19
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 10, iteration: 1/100, moves: 93668, ncost: 1.8034753895843303e+19
Run: 10, iteration: 2/100, moves: 60502, ncost: 1.793147617778733e+19
Run: 10, iteration: 3/100, moves: 36375, ncost: 1.7895804298190567e+19
Run: 10, iteration: 4/100, moves: 21369, ncost: 1.788363089946463e+19
Run: 10, iteration: 5/100, moves: 12320, ncost: 1.787958745641742e+19
Run: 10, iteration: 6/100, moves: 7071, ncost: 1.7878241499623223e+19
Run: 10, iteration: 7/100, moves: 4090, ncost: 1.7877787217831518e+19
Run: 10, iteration: 8/100, moves: 2475, ncost: 1.787762471758048e+19
Run: 10, iteration: 9/100, moves: 1450, ncost: 1.7877569706436215e+19
Run: 10, iteration: 10/100, moves: 787, ncost: 1.7877552592950985e+19
Run: 10, iteration: 11/100, moves: 502, ncost: 1.7877545710238188e+19
Run: 10, iteration: 12/100, moves: 288, ncost: 1.7877543374879912e+19
Run: 10, iteration: 13/100, moves: 166, ncost: 1.7877542654950664e+19
Run: 10, iteration: 14/100, moves: 75, ncost: 1.787754251054619e+19
Run: 10, iteration: 15/100, moves: 31, ncost: 1.7877542480190786e+19
Run: 10, iteration: 16/100, moves: 19, ncost: 1.7877542470872383e+19
Run: 10, iteration: 17/100, moves: 15, ncost: 1.7877542465073148e+19
Run: 10, iteration: 18/100, moves: 7, ncost: 1.7877542463793795e+19
Run: 10, iteration: 19/100, moves: 0, ncost: 1.7877542463793795e+19
Best run was number 1

In [ ]:
# Exportar el dataframe con los clusters como csv
df.to_csv('data/tablas/dfCLUSTERS2018.csv', sep=';', encoding='latin-1')